basePath: /api/v1
definitions:
  account.Account:
    properties:
      address:
        type: string
      age:
        type: integer
      gender:
        type: string
      id:
        type: string
      name:
        type: string
      phone:
        type: string
      status:
        type: string
    type: object
  account.Login:
    properties:
      email:
        type: string
      senha:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: This API can create and search account of users
  title: Account management API
  version: "1.0"
paths:
  /account:
    post:
      consumes:
      - application/json
      description: create one new user account
      parameters:
      - description: Account details
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.Account'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create Account
      tags:
      - account
  /account/{id}:
    get:
      consumes:
      - application/json
      description: Returns data for a specific account by ID
      parameters:
      - description: ID of the account
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/account.Account'
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search account by Id
      tags:
      - account
  /authentication:
    post:
      consumes:
      - application/json
      description: Authenticate user and return a JWT token
      parameters:
      - description: Login credentials
        in: body
        name: credentials
        required: true
        schema:
          $ref: '#/definitions/account.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Authentication Account
      tags:
      - account
  /signup:
    post:
      consumes:
      - application/json
      description: Creating a new user record in the database
      parameters:
      - description: Login details
        in: body
        name: account
        required: true
        schema:
          $ref: '#/definitions/account.Login'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad Request
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create New User
      tags:
      - account
swagger: "2.0"
